# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diagnostico_rnc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import keras
import numpy as np
from tensorflow.keras.preprocessing.image import load_img, img_to_array

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMainWindow

class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(918, 468)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)

        self.fn = ""

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.marcoPrincipal = QtWidgets.QFrame(self.centralwidget)
        self.marcoPrincipal.setGeometry(QtCore.QRect(20, 20, 621, 421))
        self.marcoPrincipal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.marcoPrincipal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.marcoPrincipal.setObjectName("marcoPrincipal")

        self.visualizacionDeImagen = QtWidgets.QLabel(self.marcoPrincipal)
        self.visualizacionDeImagen.setGeometry(QtCore.QRect(0, 0, 621, 421))
        self.visualizacionDeImagen.setFrameShape(QtWidgets.QFrame.Box)
        self.visualizacionDeImagen.setText("")
        self.visualizacionDeImagen.setScaledContents(True)
        self.visualizacionDeImagen.setObjectName("visualizacionDeImagen")

        self.marcoResultadosRNC = QtWidgets.QGroupBox(self.centralwidget)
        self.marcoResultadosRNC.setGeometry(QtCore.QRect(660, 150, 251, 291))
        self.marcoResultadosRNC.setObjectName("marcoResultadosRNC")

        self.label = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.label.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.label_2.setGeometry(QtCore.QRect(140, 50, 51, 16))
        self.label_2.setObjectName("label_2")

        self.resultadoCovidMP = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.resultadoCovidMP.setGeometry(QtCore.QRect(74, 50, 55, 16))
        self.resultadoCovidMP.setText("")
        self.resultadoCovidMP.setObjectName("resultadoCovidMP")

        self.resultadoNormalMP = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.resultadoNormalMP.setGeometry(QtCore.QRect(190, 50, 55, 16))
        self.resultadoNormalMP.setText("")
        self.resultadoNormalMP.setObjectName("resultadoNormalMP")

        self.label_3 = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 121, 21))
        self.label_3.setObjectName("label_3")

        self.label_rad_tac_mp = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.label_rad_tac_mp.setGeometry(QtCore.QRect(140, 20, 121, 21))
        self.label_rad_tac_mp.setText("")
        self.label_rad_tac_mp.setObjectName("label_rad_tac_mp")

        self.label_4 = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 61, 16))
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.label_5.setGeometry(QtCore.QRect(140, 110, 51, 16))
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 121, 21))
        self.label_6.setObjectName("label_6")

        self.label_rad_tac_vgg16 = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.label_rad_tac_vgg16.setGeometry(QtCore.QRect(60, 80, 121, 21))
        self.label_rad_tac_vgg16.setText("")
        self.label_rad_tac_vgg16.setObjectName("label_rad_tac_vgg16")

        self.label_7 = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.label_7.setGeometry(QtCore.QRect(10, 170, 61, 16))
        self.label_7.setObjectName("label_7")

        self.label_8 = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.label_8.setGeometry(QtCore.QRect(140, 170, 51, 16))
        self.label_8.setObjectName("label_8")

        self.label_9 = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.label_9.setGeometry(QtCore.QRect(10, 140, 121, 21))
        self.label_9.setObjectName("label_9")

        self.label_rad_tac_vgg19 = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.label_rad_tac_vgg19.setGeometry(QtCore.QRect(60, 140, 121, 21))
        self.label_rad_tac_vgg19.setText("")
        self.label_rad_tac_vgg19.setObjectName("label_rad_tac_vgg19")

        self.label_10 = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.label_10.setGeometry(QtCore.QRect(10, 230, 61, 16))
        self.label_10.setObjectName("label_10")

        self.label_11 = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.label_11.setGeometry(QtCore.QRect(140, 230, 51, 16))
        self.label_11.setObjectName("label_11")

        self.label_12 = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.label_12.setGeometry(QtCore.QRect(10, 200, 121, 21))
        self.label_12.setObjectName("label_12")

        self.label_rad_tac_resnet50 = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.label_rad_tac_resnet50.setGeometry(QtCore.QRect(70, 200, 121, 21))
        self.label_rad_tac_resnet50.setText("")
        self.label_rad_tac_resnet50.setObjectName("label_rad_tac_resnet50")

        self.resultadoNormalVGG16 = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.resultadoNormalVGG16.setGeometry(QtCore.QRect(186, 110, 55, 16))
        self.resultadoNormalVGG16.setText("")
        self.resultadoNormalVGG16.setObjectName("resultadoNormalVGG16")

        self.resultadoCovidVGG16 = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.resultadoCovidVGG16.setGeometry(QtCore.QRect(70, 110, 55, 16))
        self.resultadoCovidVGG16.setText("")
        self.resultadoCovidVGG16.setObjectName("resultadoCovidVGG16")

        self.resultadoNormalVGG19 = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.resultadoNormalVGG19.setGeometry(QtCore.QRect(186, 170, 55, 16))
        self.resultadoNormalVGG19.setText("")
        self.resultadoNormalVGG19.setObjectName("resultadoNormalVGG19")

        self.resultadoCovidVGG19 = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.resultadoCovidVGG19.setGeometry(QtCore.QRect(70, 170, 55, 16))
        self.resultadoCovidVGG19.setText("")
        self.resultadoCovidVGG19.setObjectName("resultadoCovidVGG19")

        self.resultadoNormalResNet = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.resultadoNormalResNet.setGeometry(QtCore.QRect(186, 230, 55, 16))
        self.resultadoNormalResNet.setText("")
        self.resultadoNormalResNet.setObjectName("resultadoNormalResNet")

        self.resultadoCovidResNet = QtWidgets.QLabel(self.marcoResultadosRNC)
        self.resultadoCovidResNet.setGeometry(QtCore.QRect(70, 230, 55, 16))
        self.resultadoCovidResNet.setText("")
        self.resultadoCovidResNet.setObjectName("resultadoCovidResNet")

        self.botonCargarImagen = QtWidgets.QPushButton(self.centralwidget)
        self.botonCargarImagen.setGeometry(QtCore.QRect(660, 50, 121, 31))
        self.botonCargarImagen.setObjectName("botonCargarImagen")
        self.botonCargarImagen.clicked.connect(self.cargarImagen)

        self.realizarPrediccion = QtWidgets.QPushButton(self.centralwidget)
        self.realizarPrediccion.setGeometry(QtCore.QRect(790, 50, 121, 31))
        self.realizarPrediccion.setObjectName("realizarPrediccion")
        self.realizarPrediccion.clicked.connect(self.predecirImagen)
        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.modelo_personalizado = keras.models.load_model("../Modelos RNC/best_modelo_personalizado.h5")
        self.modelo_vgg16 = keras.models.load_model("../Modelos RNC/best_modelo_vgg16.h5")
        self.modelo_vgg19 = keras.models.load_model("../Modelos RNC/best_modelo_vgg19.h5")
        self.modelo_resnet50 = keras.models.load_model("../Modelos RNC/best_modelo_resnet50.h5")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Diagnóstico RNC"))
        self.marcoResultadosRNC.setTitle(_translate("MainWindow", "Resultados"))
        self.label.setText(_translate("MainWindow", "COVID-19:"))
        self.label_2.setText(_translate("MainWindow", "Normal:"))
        self.label_3.setText(_translate("MainWindow", "Modelo Pesonalizado"))
        self.label_4.setText(_translate("MainWindow", "COVID-19:"))
        self.label_5.setText(_translate("MainWindow", "Normal:"))
        self.label_6.setText(_translate("MainWindow", "VGG16"))
        self.label_7.setText(_translate("MainWindow", "COVID-19:"))
        self.label_8.setText(_translate("MainWindow", "Normal:"))
        self.label_9.setText(_translate("MainWindow", "VGG19"))
        self.label_10.setText(_translate("MainWindow", "COVID-19:"))
        self.label_11.setText(_translate("MainWindow", "Normal:"))
        self.label_12.setText(_translate("MainWindow", "ResNet50"))
        self.botonCargarImagen.setText(_translate("MainWindow", "Cargar Imagen"))
        self.realizarPrediccion.setText(_translate("MainWindow", "Realizar Predicción"))

    def cargarImagen(self):
        fileName, _ = QFileDialog.getOpenFileName(self,"Buscar Imágenes", "","Archivos PNG (*.png);; Archivos JPG (*.jpg);; Archivos JPEG (*.jpeg)")
        if fileName:
            self.fn = fileName
            self.visualizacionDeImagen.setPixmap(QtGui.QPixmap(fileName))

    def predecirImagen(self):
        image_299 = load_img(self.fn,target_size= (299, 299))
        image_224 = load_img(self.fn,target_size= (224, 224))

        image_array_299 = img_to_array(image_299) / 255
        image_array_299 = np.array([image_array_299])

        image_array_224 = img_to_array(image_224) / 255
        image_array_224 = np.array([image_array_224])

        prediccion_modelo_personalizado = self.modelo_personalizado.predict(image_array_299) * 100
        prediccion_modelo_vgg16 = self.modelo_vgg16.predict(image_array_224) * 100
        prediccion_modelo_vgg19 = self.modelo_vgg19.predict(image_array_224) * 100
        prediccion_modelo_resnet50 = self.modelo_resnet50.predict(image_array_224) * 100

        if np.argmax(prediccion_modelo_personalizado[0]) <= 1:
            self.label_rad_tac_mp.setText("Radiografía")
            self.resultadoCovidMP.setText(str(round(prediccion_modelo_personalizado[0][0],2)) + "%")
            self.resultadoNormalMP.setText(str(round(prediccion_modelo_personalizado[0][1],2)) + "%")
        else:
            self.label_rad_tac_mp.setText("TAC")
            self.resultadoCovidMP.setText(str(round(prediccion_modelo_personalizado[0][2],2)) + "%")
            self.resultadoNormalMP.setText(str(round(prediccion_modelo_personalizado[0][3],2)) + "%")

        if np.argmax(prediccion_modelo_vgg16[0]) <= 1:
            self.label_rad_tac_vgg16.setText("Radiografía")
            self.resultadoCovidVGG16.setText(str(round(prediccion_modelo_vgg16[0][0],2)) + "%")
            self.resultadoNormalVGG16.setText(str(round(prediccion_modelo_vgg16[0][1],2)) + "%")
        else:
            self.label_rad_tac_vgg16.setText("TAC")
            self.resultadoCovidVGG16.setText(str(round(prediccion_modelo_vgg16[0][2],2)) + "%")
            self.resultadoNormalVGG16.setText(str(round(prediccion_modelo_vgg16[0][3],2)) + "%")

        if np.argmax(prediccion_modelo_vgg19[0]) <= 1:
            self.label_rad_tac_vgg19.setText("Radiografía")
            self.resultadoCovidVGG19.setText(str(round(prediccion_modelo_vgg19[0][0],2)) + "%")
            self.resultadoNormalVGG19.setText(str(round(prediccion_modelo_vgg19[0][1],2)) + "%")
        else:
            self.label_rad_tac_vgg19.setText("TAC")
            self.resultadoCovidVGG19.setText(str(round(prediccion_modelo_vgg19[0][2],2)) + "%")
            self.resultadoNormalVGG19.setText(str(round(prediccion_modelo_vgg19[0][3],2)) + "%")

        if np.argmax(prediccion_modelo_resnet50[0]) <= 1:
            self.label_rad_tac_resnet50.setText("Radiografía")
            self.resultadoCovidResNet.setText(str(round(prediccion_modelo_resnet50[0][0],2)) + "%")
            self.resultadoNormalResNet.setText(str(round(prediccion_modelo_resnet50[0][1],2)) + "%")
        else:
            self.label_rad_tac_resnet50.setText("TAC")
            self.resultadoCovidResNet.setText(str(round(prediccion_modelo_resnet50[0][2],2)) + "%")
            self.resultadoNormalResNet.setText(str(round(prediccion_modelo_resnet50[0][3],2)) + "%")

        print(np.argmax(prediccion_modelo_personalizado[0]))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
